### ISSUE TITLE
[Peer Testing] bug report

### ISSUE THREAD

**Issue by snusun** [swsnu/swpp2020-team7#104]
여기에 작성해주시면 감사하겠습니다!!

**Comment by fjqlddb06** [comment]
![image](https://user-images.githubusercontent.com/24264246/101754540-31292a00-3b17-11eb-9f6a-7fd9c1dbca4c.png)
버그는 아니지만 오늘의 재료에 많은 재료가 들어가면 메모장을 초과해서 계속 내려가는 것 같습니다.

**Comment by shapespeare** [comment]
![image](https://user-images.githubusercontent.com/26834464/101754653-4f8f2580-3b17-11eb-85c6-d396663e46da.png)

오늘의 재료를 하나 추가했을 때 위와 같이 겹쳐져서 나오는 것 같습니다. 두 개부턴 괜찮은데 다시 하나를 삭제하니 마찬가지로 돌아갑니다.

**Comment by fjqlddb06** [comment]
![image](https://user-images.githubusercontent.com/24264246/101754950-a85ebe00-3b17-11eb-9487-703878d6757b.png)
좋아요를 누를때와 해제할 때 둘다 같은 메세지가 뜹니다.

**Comment by curious-curie** [comment]
버그는 아닌데요 오늘의 재료를 추가한다음에 레시피 추천을 어디서 받을 수 있는지 모르겠어요! 안내가 되어있으면 좋을 것 같아요

**Comment by Namnamseo** [comment]
<오늘의 재료>에 들어간 재료를 바탕으로 추천이 나오는 게 맞나요..? 재료를 바꿨을 때 레시피 추천이 그대로인 것 같습니다!

**Comment by GooJinSun** [comment]
![image](https://user-images.githubusercontent.com/37523788/101755103-d47a3f00-3b17-11eb-9ec8-487696177640.png)
우리동네 장터에서 검색 후 article을 클릭하면
https://naengpa.shop/articles/:5
url로 링크되면서 아무 화면도 뜨지 않는 것 같아요!

**Comment by ihatedebug** [comment]
우리동네 장터에 품목을 누르면 빈 화면에서 작동하지 않습니다

**Comment by creambread-duck** [comment]
![image](https://user-images.githubusercontent.com/70693762/101755247-fecbfc80-3b17-11eb-932c-3e36af4b0587.png)
거래글을 올렸는데 두개가 올라갔고 필터에서 나눔을 적용해도 거래글이 보여요

**Comment by koyrkr** [comment]
버그 포함 테스팅하면서 들었던 의문사항 정리해서 올립니다!
- 경기도는 지역 설정이 안되는 건가요?
- 레시피 좋아요가 눌러지지 않는 것 같습니다!
- 냉장고에서 오늘의 재료로 추가할때 별 토글이랑 추가되는 부분이 sync가 안맞는 것 같습니다

**Comment by kslim99** [comment]
우리동네 장터에 글을 쓰고 등록을 했는데 창 안 넘어가고 나와서 검색해도 글이 안 보이는 것 같습니다

**Comment by GooJinSun** [comment]
![image](https://user-images.githubusercontent.com/37523788/101755432-333fb880-3b18-11eb-9160-26fb79047f7f.png)
레시피 댓글 기능은 아직 구현되지 않은건가요??

**Comment by junhyekh** [comment]
<img width="1367" alt="스크린샷 2020-12-10 오후 6 47 25" src="https://user-images.githubusercontent.com/70698100/101755499-481c4c00-3b18-11eb-8ecb-e1f033704389.png">
나눔 후에 사진이 깨진는 현상이 있습니다

**Comment by creambread-duck** [comment]
![image](https://user-images.githubusercontent.com/70693762/101755559-5a968580-3b18-11eb-88e7-344f9431691c.png)
거래글을 누를시 그림이 안보여요

**Comment by gratus907** [comment]
브라우저 safari, macOS Catalina입니다.

음식을 검색해서 like를 누를 때 다음과 같은 에러가 발생합니다. 
![image](https://user-images.githubusercontent.com/20734325/101754851-8b29ef80-3b17-11eb-9944-417883c181af.png)

돋보기 아이콘과 거래 교환 나눔이 겹쳐서 렌더링됩니다.
![image](https://user-images.githubusercontent.com/20734325/101754908-9e3cbf80-3b17-11eb-8271-a2a93d85bec6.png)

글 등록이 잘 눌리지 않습니다. (등록을 클릭해도 아무 일도 일어나지 않음)
![image](https://user-images.githubusercontent.com/20734325/101755282-068ba100-3b18-11eb-8705-3451a9ec958e.png)

**Comment by ssm0318** [comment]
<img width="444" alt="스크린샷 2020-12-10 오후 6 49 31" src="https://user-images.githubusercontent.com/25769209/101755638-7437cd00-3b18-11eb-9b6f-1347d3f3e740.png">

이 부분이 사알짝 깨지는 것 같아요!

**Comment by Jong25** [comment]
![스크린샷 2020-12-10 오후 6 47 41](https://user-images.githubusercontent.com/49151604/101755429-320e8b80-3b18-11eb-80e5-8cf3c1294eba.png)
의도하신건지 모르겠지만 닭볶음탕 재료에 감 (과일 감이 아닌 듯 합니다)이 들어있네요ㅎㅎ
재료를 레시피 텍스트에서 자동으로 추출하는 것 같은데 미리 정해진 재료가 아닌 경우에 문제가 되지 않을까 싶습니다!

**Comment by ihatedebug** [comment]
![image](https://user-images.githubusercontent.com/57564205/101755776-a1847b00-3b18-11eb-8a9e-6bd012de0376.png)
이부분은 에러인가요 구현이 안된건가요?

**Comment by ssm0318** [comment]
버그는 아닌데요 메시지는 어떻게 주고 받는건가요? 거래할 때만 쓰이는건가요?

**Comment by Lemarais** [comment]
제가 이것저것 저도 구현해 본 입장으로써 넘기려 했지만
사진이 확장자가 안맞는 다는 이유로 써놓은 게 다 날아갔다는게 너무 마음이 아픕니다
업로드 할 때 확장자가 잘못되었다고 알려주거나 아니면 확장자가 다르다고 해서 내용을 다 날리지 않았으면 좋겠습니다

**Comment by creambread-duck** [comment]
![image](https://user-images.githubusercontent.com/70693762/101755978-ddb7db80-3b18-11eb-8e06-793e28c52d0f.png)
스팸주먹밥 재료에 가지가 들어가있어요 너무 끔찍합니다 ㅠㅠㅠ

**Comment by ssm0318** [comment]
스팸주먹밥 가짘ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

댓글이 많아서 제가 놓쳤을 수도 있는데 재료 태그를 눌러도 안 눌려져서 아쉬워요 해당 재료를 사용한 다른 레시피들도 보고 싶습니다!
hover했을 때 손 모양으로 바뀌면서 클릭 가능한 듯 보여가지고 더 아쉽네요ㅜㅜ

<img width="622" alt="스크린샷 2020-12-10 오후 6 52 37" src="https://user-images.githubusercontent.com/25769209/101756151-1061d400-3b19-11eb-8651-4b33b05be1a9.png">

**Comment by junepaykim** [comment]
1. 장터에 게시글을 썼는데 보이지 않습니다. 거래 교환 나눔을 누르면 한번은 나오는데 두번 세번 눌러보면 없어졌다가 다시 나오지 않습니다.
2. gif랑 png 올리고 싶어요~
3.

**Comment by gratus907** [comment]
![image](https://user-images.githubusercontent.com/20734325/101756190-1ce62c80-3b19-11eb-9aab-60c48763d8ef.png)
실제로 3개의 전분이 있나요? 에러인 것 같습니다.

**Comment by GooJinSun** [comment]
재료 추천 기능이 재미있네요!
재료 추천을 받고 나서 요리명이나 재료를 수정할 수 있으면 좋을 것 같습니다!!
