### ISSUE TITLE
Needs to make an actions/index.ts file for actionCreators

### ISSUE THREAD

**Issue by vegeshop** [swsnu/swpp2020-team7#15]
For now, actions are scattered in multiple files in store/actions folder.
If there is an **index.ts file just collecting all actions and exporting them all in a collection**, we can just import actionCreators from that file. It would be convenient and efficient.

**Comment by lynn0506** [comment]
`/* User actions */
export {
	checkLogin,
	signup,
	login,
	logout,
	getUserList,
	getUser,
	editUser,
	deleteUser,
} from './user';

/* Fridge actions */
export { getFridge, addFridge, editFridge } from './fridge';

/* Recipe actions */
export { getRecipeList, getRecipe, createRecipe, deleteRecipe, editRecipe } from './recipe';

/* Ingredient actions */
export {
	getIngredientList,
	getIngredient,
	addIngredient,
	deleteIngredient,
	editIngredient,
} from './ingredient';

/* Article actions */
export { getArticleList, getArticle, createArticle, deleteArticle, editArticle } from './article';

/* Comment actions */
export { getCommentList, getComment, addComment, deleteComment, editComment } from './comment';
`
