### ISSUE TITLE
My Fridge Page - Icons(copyright)

### ISSUE THREAD

**Issue by lynn0506** [swsnu/swpp2020-team7#17]
We planned to use Free Icons found on the Internet for 'my fridge' page. However, because of the copyright, we have to add attribution link. Alternatively, we've decided to create our own Icons for "Fridge, Memo and Food Categories". 재인 already made Memo icon and she is still working on Fridge Icon. 
For "Food Category", however, it is better to look for other free icons, since there's not enough time to create all the icons!!!

**Comment by janejane516** [comment]
We decided to use the free icons from "Flaticon" for Food Category and add the copyright information as the footer of 'my fridge' page. Also I made Memo and Fridge Icons.
