### ISSUE TITLE
[Frontend] My page url 관련 문제

### ISSUE THREAD

**Issue by snusun** [swsnu/swpp2020-team7#58]
11월 25일 수요일 회의에서 Header의 My page button을 눌렀을 때 바로 user info가 뜨도록 하기로 결정했는데, 
그때의 url을 어느 것으로 결정하는 것이 좋을까요? 
 * http://localhost:3000/@:username/info
 * http://localhost:3000/@:username
의견 주신대로 진행하도록 하겠습니다!

**Comment by snusun** [comment]
두번째 드릴 말씀은 button color에 관한 것인데, 본래 template에서는 
![Screenshot from 2020-11-27 03-54-48](https://user-images.githubusercontent.com/60461200/100384854-77d14b80-3064-11eb-8783-a010c6c29334.png)
현재 page에 해당하는 버튼의 색이 회색이 되도록 했었습니다. 그런데 구현 방향을 조금 바꾸다보니 버튼이 있는 부분을 Tap이라는 component로 만들게 되었는데, 이때 페이지마다 버튼의 색을 다르게 하기가 어렵습니다.. 혹시 좋은 방법이 생각나신다면 알려주시면 감사하겠습니다. 방법이 없다면 수요일 회의 때 은주님께서 건의하셨던 것처럼 버튼에 마우스를 올렸을 때에만 색이 변하게 하는 방법도 있는데, 의견 주시면 감사하겠습니다!

**Comment by janejane516** [comment]
1. /info 붙은 것
2. 페이지마다 버튼 색이 바뀌는 것이 사실 가장 깔끔해보이는데요, 같이 해결해보면 좋을 것 같아요.

**Comment by lynn0506** [comment]
1. 저도 info가 붙은 것이 좋아요! 
2. 만약에 버튼 색을 유지하고 싶으면, redux store에서 어떤 탭을 클릭하고 있는지 저장해두는 state가 있어도 좋을 것 같아요! 그럼 userselecter를 사용해서 클릭된 버튼만 색상을 다르게 주는 방법도 있습니다. 혹은 
<img width="558" alt="Screen Shot 2020-11-27 at 3 46 34 PM" src="https://user-images.githubusercontent.com/52408635/100419357-be0bc680-30c7-11eb-85d6-476b9b581da8.png">
<img width="563" alt="Screen Shot 2020-11-27 at 3 46 59 PM" src="https://user-images.githubusercontent.com/52408635/100419381-cc59e280-30c7-11eb-8b7d-c1ef9106cdb7.png">

이런 식으로 props로 어떤 버튼이 눌리고 있는지 보내주는 방법이 있습니다! 개인적으로는 후자가 더 깔끔할 것 같아요 ㅎ_ㅎ RecipeList, TodayRecipe, Recipe 을 참고해주시면 됩니다.

**Comment by snusun** [comment]
네 참고해서 수정사항 반영하도록 하겠습니다! 감사합니다.
