### ISSUE TITLE
[Frontend] Regional Setting 

### ISSUE THREAD

**Issue by lynn0506** [swsnu/swpp2020-team7#60]
지역설정과 관련된 부분을 조금 구체적으로 논의를 해야할 것 같습니다. 

1. 원래 검색을 사용하기로 했었는데요! 그 검색 범위에 제한을 두지 않으면 유저가 제대로된 input을 입력한다는 조건이 없어서 지도에 표시할 때 문제가 됩니다.
  + 서울로 제한으로 두고 동 리스트를 데이터 베이스에 저장해두고 비교를 하는건 어떤가요? 혹은 다른 방법이 있을까요?
  + 추가적으로 select box로 '구'와 '동'을 선택하도록 할까요,,,? 
  + 혹은 보통 지역 검색시에는 리스트가 뜨고 선택가능하도록 하는데, dropbox 형식으로 리스트가 뜨고 선택하는 것도 가능합니다! 
  + 아니면, 검색만 가능하게 해도 됩니다.

<img width="836" alt="Screen Shot 2020-11-27 at 9 42 30 PM" src="https://user-images.githubusercontent.com/52408635/100450724-7f8eff80-30f9-11eb-9ef7-1b69035e6040.png">

2. 슬라이더 좁음 중간 넓음의 범위를 명확히 해야할 것 같습니다! 일단은 1km, 5km, 10km 정도로 구현을 해보려 합니다...!

3. 아래 동작 상세에서 추가해야할 부분이 있나요? 
    + 일단 유저가 동을 입력하면, 지도에 해당 중심지역에 핀이 꽂힌다. 
    + 슬라이더로 구역의 범위를 조절하면, 지도가 넓어지거나 좁아진다. ( 슬라이더 바로만 범위 설정이 가능한가요 아니면, 지도에서 동작도 가능한가요?)
    + back으로 중심지의 *위도, *경도, *범위를 보내면, PostGIS GeoDjango를 사용해서 정렬된 장소들 리스트를 추출한다. => 장터 게시판에서 게시물 sorting에 사용한다.

**Comment by snusun** [comment]
1. 제가 템플릿을 만들 때 그 부분을 만들어두었었는데, 문서에 올리면서 빼고 올리다보니 설명이 부족했던 것 같습니다.
저도 유저가 제대로 된 인풋을 입력하지 않는 것을 가정하여 
 * 만약 '구'를 검색할 경우 해당 구에 있는 모든 동들이 'ㅇㅇ구 ㅇㅇ동' 이런 형태로 검색창 아래에 list로 뜨고
 * 만약 '동'을 검색할 경우 해당 동을 가지고 있는 모든 구들이 'ㅇㅇ구 ㅇㅇ동' 형태로 검색창 아래에 list로 뜨게 하는 것을 처음에 구상했었습니다!
이 때 유저는 list가 뜰 때 그 선택지에서만 고를 수 있어서 만약 잘못된 인풋을 입력한다면 지역을 선택할 수 없게 됩니다. 
저희가 저번에 말했듯이 전국을 하는 것은 행정구역 명칭 문제도 있고 개수도 많아서 서울로 한정짓는다면 좋을 것 같습니다...

2. 슬라이더 범위는 1km, 3km, 5km가 어떨까요? 냉파 특성상 자취생이 이용하게 될텐데 10km라면 도보로 이동하기가 힘들 것 같습니다.. 만약 이 범위가 너무 좁아서 동의 개수가 차이가 나지 않는다면 그때 범위를 넓히는 것이 어떨까요?

3. 
 * 유저가 동을 입력하여 list에서 선택하면 해당 중심 지역에 핀이 꽂히면 좋겠습니다.
 * 제가 구상할 때에는 슬라이더로만 조절하게 했습니다!
 * 정렬된 장소 리스트를 유저 단에서 가지고 있어서 장터 게시판에 저장된 지역 정보를 토대로 sorting하면 좋을 것 같습니다.

제가 구상한 부분이라 설명히 충분히 전달되지 않은 점 죄송합니다. 
혹시 더 궁금하신 점이 생기신다면 연락 주세요:)

**Comment by lynn0506** [comment]
앗 충분히 ㅎㅎ 답이 되었습니다! 다른 분들 동의하시면 이대로 진행해도 좋을 것 같습니다! 
그러면 데이터베이스 정리가 필요해서 해당 모델 backend까지 구축하겠습니다~~

**Comment by janejane516** [comment]
동의합니다.
