### ISSUE TITLE
The number of food categories in Food groups detection feature

### ISSUE THREAD

**Issue by snusun** [swsnu/swpp2020-team7#66]
food groups detection API를 끌어오는 데 성공했습니다!
근데 여기서 논의해볼 게 있습니다.
원래 카테고리를 추출하면 여러 음식이 detect되어 일정 percentage 이상인 group들을 반영하자고 했었는데, 
실제로 사용을 해보니 하나의 group만 detect하고 비율이 거의 100%에 가깝더라구요.
그래서 다시 처음대로 food category는 하나만 띄우려고 하는데 괜찮을까요?

**Comment by lynn0506** [comment]
네! 좋아요 :)

**Comment by janejane516** [comment]
저도 좋습니다!
