### ISSUE TITLE
[Frontend] OnkeyDown  Event Bug

### ISSUE THREAD

**Issue by lynn0506** [swsnu/swpp2020-team7#72]
<img width="509" alt="Screen Shot 2020-12-05 at 4 07 47 AM" src="https://user-images.githubusercontent.com/52408635/101204465-9a401600-36af-11eb-899d-6d3bc8c9be3b.png">

<img width="482" alt="Screen Shot 2020-12-05 at 4 13 11 AM" src="https://user-images.githubusercontent.com/52408635/101204832-336f2c80-36b0-11eb-9644-a22db5b0aff3.png">

OnKeyDown={(e) => {...}} 이벤트를 사용할 때, if(e.key == 'Enter') {...}로 엔터 이벤트를 사용하던 중에 엔터가 두 번 눌려서 채팅창 입력이 두 번 발생하는 Bug(?)를 발견했습니다. 찾아보니 1 byte에 1 event를 실행해야하는데 한글 입력 시에 문제가 되는 것 같습니다. OnKeyDown event 대신에 **OnKeyPress** 를 사용하면 해당 문제가 없으므로, 검색을 하는 이벤트에서는 꼭 변경해주세요~~~

**Comment by snusun** [comment]
네! 문제 공유 감사합니다!
